#!/bin/sh

if [ ! -d "$HOME/.pb" ]; then
  echo "Installing dotfiles for the first time."
  git clone https://github.com/pburtchaell/dotfiles.git "$HOME/.pb"
  cd "$HOME/.pb"
  [ "$1" = "ask" ] && export ASK="true"
  make install
else
    echo "Dotfiles are already installed."
fi
