#!/bin/sh
#
# This script configures Node development setup. Note that
# nvm is installed by the Homebrew install script.
#
# Also, I would highly reccomend *not* installing your Node.js build
# tools, e.g., Grunt, gulp, WebPack, or whatever you use, globally.
# Instead, install these as local devDepdencies on a project-by-project
# basis. Most Node CLIs can be run locally by using the executable file in
# "./node_modules/.bin". For example:
#
#   `npm bin`/webpack --config webpack.local.config.js
#
if test ! $(which nvm)
then
  echo "Installing a stable version of Node."

  # Install the stable version of node.
  nvm install stable

  # Use the stable version of node by default.
  nvm alias default stable
fi
