# Default oh-my-zsh config
# Last Updated: 2019-10-27

# Path to your oh-my-zsh installation
export ZSH=/Users/pburtchaell/.oh-my-zsh

# Yarn Package Manager
# Reference: https://yarnpkg.com/en/
export PATH="$PATH:`yarn global bin`"

# Zsh Theme
# https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Zsh Plugins
plugins=(git)
source $ZSH/oh-my-zsh.sh

# Aliases
alias code="cd ~/Repositories"
alias fuckit="echo \"Removing node_modules (╯°□°）╯︵ ┻━┻ \" && rm -rf node_modules"
alias pg-start="pg_ctl -D /usr/local/var/postgres start"
alias pg-stop="pg_ctl -D /usr/local/var/postgres stop"
